In [1]:
import numpy as np
from sklearn.decomposition import FastICA

# Step-1: Create 2 simple independent signals
S=np.array([[1,1],[2,-1],[3,1],[4,1]])

# Step 2: Mix them
A=np.array([[1,2],[3,4]])
X=S@A.T  #Observed Mixed data

# Step 3: Apply ICA
ica=FastICA(n_components=2, random_state=0)
U=ica.fit_transform(X)
print("Original Sources:\n",S)
print("Recovered ources (approx):\n",U)

Original Sources:
 [[ 1  1]
 [ 2 -1]
 [ 3  1]
 [ 4  1]]
Recovered ources (approx):
 [[-0.81984894  1.42903234]
 [-1.10504234 -1.33374714]
 [ 0.60598672  0.24769239]
 [ 1.31890456 -0.34297759]]


In [7]:
### Implementation of Autoencoder
### This code how an autoencoder compresses 4 input into 2 hidden features and then reconstructs the original

import numpy as np
from sklearn.neural_network import MLPRegressor

# Step 1: Craete simple data (4 features)
X=np.array([[1,2,3,4],
           [2,3,4,5],
           [3,4,5,6],
            [4,5,6,7]], dtype=float)

# Step 2: Craete Autoendcoder (4->2->4)
autoencoder=MLPRegressor(hidden_layer_sizes=(2,), activation="relu",max_iter=5000, random_state=54)

# Step 3: Train to reproduce input
autoencoder.fit(X,X)

# Step 4: Reconstruct
X_reconstructed=autoencoder.predict(X)

# Step 5: Print 2D hiddem representation (the "4->2" part)
W=autoencoder.coefs_[0]    # (4*2) input -> hidden weight
b=autoencoder.intercepts_[0]
hidden_2d=np.maximum(0,X@ W+b)   # ReLU: max(0,....)

print("Original (4 features):\n",W)
print("\nHidden (2 features)",np.round(hidden_2d,2))
print("\nReconstructed:\n",np.round(X_reconstructed,2))

Original (4 features):
 [[ 0.26284756 -0.09675474]
 [ 0.26035767  0.16429598]
 [ 0.15754463  1.03712975]
 [ 0.28422837  0.59531526]]

Hidden (2 features) [[3.02 4.78]
 [3.99 6.48]
 [4.95 8.18]
 [5.92 9.88]]

Reconstructed:
 [[1.92 2.58 3.18 3.82]
 [2.41 3.25 4.09 4.99]
 [2.9  3.91 5.   6.16]
 [3.39 4.58 5.91 7.33]]


In [14]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

#Create simple dataset (fix parameters properly)
x,y = make_classification(n_samples=100,n_features=2,n_redundant=0,n_informative=2,random_state=54)

#Start with 10 labelled samples
labelled = np.arange(10)
unlabelled = np.arange(10,100)
model = LogisticRegression(solver="liblinear")

for z in range(5):
    model.fit(x[labelled],y[labelled])
    probs = model.predict_proba(x[unlabelled])[:,1]
    #pick most unceratin sample
    query = np.argmin(np.abs(probs-0.5))
    #move that sample to labelled set
    labelled = np.append(labelled,unlabelled[query])
    unlabelled = np.delete(unlabelled,query)
    
    print("Iteration: ",z+1, "|Labelled size: ", len(labelled))

Iteration:  1 |Labelled size:  11
Iteration:  2 |Labelled size:  12
Iteration:  3 |Labelled size:  13
Iteration:  4 |Labelled size:  14
Iteration:  5 |Labelled size:  15
